import sys
import os
#Disc:  Reads a lst file generated by me
#I/P:   filename, line no to start to reading from
def Read_inter_file(file_name,from_):
    data=[]
    try:
        fp=open(file_name,"r")
    except IOError:
        print("File Not open")
    line_no=0
    for line in fp.readlines():
        line_no+=1
        if len(line.split())==0 and from_==0:
            break
        if from_>0:
            if line_no>=from_:
                data.append([line_no-from_,line.split()])
        else:
            if line_no>1:
                data.append([line_no,line.split()])
    return data,line_no
#Disc:  Write in output file 
#I/P:   file name and input data and line no
def Write_combine_file(file_name,data,ln):
    fp=open(file_name,"a+")
    for line in data:
        fp.write(str(ln)+"\t")
        ln+=1
        if len(line[1])<4:
            fp.write("\t\t")
        for d in range(1,len(line[1])):
            fp.write(str(line[1][d])+"\t")
        fp.write("\n")
    fp.write("\n")
    fp.close()
    return ln
def Write_lst_info(file_name,data):
    fp=open(file_name,"a+")
    for d in data:
        fp.write(str(d))
def f(l,n):
    if len(l[1])<n:
        temp=[l[0],[0]+l[1]]
        return temp
    return l
#Disc:  get two files and write op in third file
def Combine(file1,file2):
    #Read first file(symbol table)
    symbol_table_1,to_line_no1=Read_inter_file(file1,0)
    symbol_table_2,to_line_no2=Read_inter_file(file2,0)
    symbol_table_1=list(map((lambda l: f(l,7)),symbol_table_1))
    symbol_table_2=list(map((lambda l: f(l,7)),symbol_table_2))
    os.system("rm combine_inter_file.txt")
    to_line=Write_combine_file("combine_inter_file.txt",symbol_table_1,1);
    to_line=Write_combine_file("combine_inter_file.txt",symbol_table_2,to_line+1);
    LST_data_file1,ln=Read_inter_file(file1,to_line_no1)
    LST_data_file2,ln=Read_inter_file(file1,to_line_no2)
    to_line=Write_combine_file("combine_inter_file.txt",LST_data_file1,to_line+1)
    to_line=Write_combine_file("combine_inter_file.txt",LST_data_file2,to_line+1)
Combine(sys.argv[1],sys.argv[2])
print("Check combine_inter_file.txt for output")
